spring.application.name=markify

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/markify
spring.datasource.username=postgre
spring.datasource.password=4563
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


